name: Bandit Secure Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 15 * * 4'

permissions:
  contents: read
  security-events: write

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask bandit

      - name: Run Bandit scan
        run: |
          bandit -r . -f json -o bandit-results.json --exit-zero

      - name: Download bandit_to_sarif.py script directly
        run: |
          curl -L -o bandit_to_sarif.py https://raw.githubusercontent.com/microsoft/bandit-to-sarif/main/bandit_to_sarif.py

      - name: Convert Bandit JSON to SARIF
        run: |
          python3 bandit_to_sarif.py -i bandit-results.json -o bandit-results.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-results.sarif
