name: Bandit Secure Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 15 * * 4'  # 매주 목요일 15:20 UTC

permissions:
  contents: read
  security-events: write

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask bandit

      - name: Run Bandit scan (JSON format)
        run: |
          bandit -r . -f json -o bandit-results.json --exit-zero

      - name: Download bandit-to-sarif binary and convert
        run: |
          curl -L -o bandit-to-sarif "https://github.com/microsoft/bandit-to-sarif/releases/download/v1.0.0/bandit-to-sarif-linux"
          chmod +x bandit-to-sarif
          ./bandit-to-sarif -i bandit-results.json -o bandit-results.sarif

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-results.sarif
