name: Bandit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 15 * * 4'

jobs:
  bandit:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit scan
        run: |
          bandit -r . -f sarif -o bandit-results.sarif

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-results.sarif
